### ISSUE TITLE
EMの追加

### ISSUE THREAD

**Issue by YuyaNishikawa** [abdominal6/Gotanda-Curries#22]
当社では、サービスの急拡大に伴い、エンジニアが急増中。さらにエンジニアの従業員体験を改善し、新たな仲間を迎え入れるためにも、エンジニアマネージャーの存在が必要です。

**Comment by YuyaNishikawa** [comment]
こちら、自分で担当します！

**Comment by tomohiro3** [comment]
タイトルは求人名のみにしてください

**Comment by nokv** [comment]
@YuyaNishikawa 
イシューのタイトルを変更し、作業は完了したと思うのでcloseしちゃいましょう！

**Comment by YuyaNishikawa** [comment]
done

**Comment by abdominal6** [comment]
https://github.com/abdominal6/Gotanda-Curries/pull/34
