### ISSUE TITLE
新しいコックさんを募集！

### ISSUE THREAD

**Issue by Ikuo-Niimoto** [abdominal6/Gotanda-Curries#24]
ビーフカレー屋さんのコックさんを募集します！
なぜ募集するのか？
ビーフカレーのお店の２号店進出のための店長候補です！

以下条件
・レシピを守れる方
・料理が大好きな方
・料理をより良くしていく向上心のある方

**Comment by Ikuo-Niimoto** [comment]
こちら、新本が担当します！

**Comment by abdominal6** [comment]
https://github.com/abdominal6/Gotanda-Curries/pull/44
