### ISSUE TITLE
夏野菜カレーを考案してメニューに入れて作れるようにする

### ISSUE THREAD

**Issue by abdominal6** [abdominal6/Gotanda-Curries#6]
やること
- [ ] メニューにカレーを追加
- [ ] レシピを追加

**Comment by YuyaNishikawa** [comment]
こちら担当します。

**Comment by abdominal6** [comment]
https://github.com/abdominal6/Gotanda-Curries/pull/32
https://github.com/abdominal6/Gotanda-Curries/pull/28
