### ISSUE TITLE
甘口カレーを考案してメニューに入れて作れるようにする

### ISSUE THREAD

**Issue by abdominal6** [abdominal6/Gotanda-Curries#9]
## やること
- [ ] メニューにカレーを追加
- [ ] レシピを追加

**Comment by yunahirai** [comment]
こちら担当します。

**Comment by abdominal6** [comment]
fixed #12

**Comment by nokv** [comment]
https://github.com/abdominal6/Gotanda-Curries/pull/33 で対応完了したのclose
